// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfupNCnxBtRMLqxVAU0SHrLqyXo1Ori8Y',
    appId: '1:872083281681:web:c2ce456457213cebd41eb0',
    messagingSenderId: '872083281681',
    projectId: 'cryptoapp-58ef0',
    authDomain: 'cryptoapp-58ef0.firebaseapp.com',
    storageBucket: 'cryptoapp-58ef0.appspot.com',
    measurementId: 'G-VRRRMJKQ3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOfSHak7E-B3R3fMv2TboaqKMjrh8pekg',
    appId: '1:872083281681:android:c4c103979df90822d41eb0',
    messagingSenderId: '872083281681',
    projectId: 'cryptoapp-58ef0',
    storageBucket: 'cryptoapp-58ef0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRDd45jQWY3NoMe_0U20mmWhPrbceeiuY',
    appId: '1:872083281681:ios:a9dff7f5db519efbd41eb0',
    messagingSenderId: '872083281681',
    projectId: 'cryptoapp-58ef0',
    storageBucket: 'cryptoapp-58ef0.appspot.com',
    iosBundleId: 'com.example.flutter1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRDd45jQWY3NoMe_0U20mmWhPrbceeiuY',
    appId: '1:872083281681:ios:a9dff7f5db519efbd41eb0',
    messagingSenderId: '872083281681',
    projectId: 'cryptoapp-58ef0',
    storageBucket: 'cryptoapp-58ef0.appspot.com',
    iosBundleId: 'com.example.flutter1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfupNCnxBtRMLqxVAU0SHrLqyXo1Ori8Y',
    appId: '1:872083281681:web:0d03c38a5e89c117d41eb0',
    messagingSenderId: '872083281681',
    projectId: 'cryptoapp-58ef0',
    authDomain: 'cryptoapp-58ef0.firebaseapp.com',
    storageBucket: 'cryptoapp-58ef0.appspot.com',
    measurementId: 'G-50M37T8S7T',
  );
}
